# Generated by Django 4.2.5 on 2024-02-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bob', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('jeremy', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('coworker1', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('coworker2', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('coworker3', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('coworker4', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('coworker5', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
