# Generated by Django 4.2.5 on 2024-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanbalance', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
