# Generated by Django 4.2.5 on 2024-02-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanbalance', '0003_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
